description: Lung_PyTorch_const
hyperparameters:
    seed: 123
    amp_mode: False
    batch_size: 32
    lr: 0.001                     # using smaller learning rate is better
    weight_decay: 1e-5
    data_root: './CheXpert-v1.0-small/'
records_per_epoch: 60000
searcher:
    name: single
    metric: val_loss
    smaller_is_better: false
    max_length:
        epochs: 1
entrypoint: model_def:LungDiseaseTrial
max_restarts: 0
