# Python version required to run the project.
python: "3.8.0"
# Dependencies required to build packages. This field is optional.
build_dependencies:
  - pip==23.0.1
  - setuptools==67.6.0
  - wheel==0.40.0
# Dependencies required to run the project.
dependencies:
  - -r ./config/env/requirements.txt